openapi: 3.0.0
info:
  title: simple-api
  version: 0.1.0

paths:
  /api/v1/login:
    post:
      responses:
        '200':
          description: A simple login!
          content:
            text/plain:
              schema:
                type: string
              example: Login from a mocked response!
      x-kusk:
        upstream:
          service:
            name: smart-home-auth
            namespace: default
            port: 8080
  /api/v1/devices:
    get:
      responses:
        '200':
          description: A simple management!
          content:
            text/plain:
              schema:
                type: string
              example: Management from a mocked response!
      x-kusk:
        upstream:
          service:
            name: smart-home-management
            namespace: default
            port: 8080
    put:
      responses:
        '200':
          description: A simple management!
          content:
            text/plain:
              schema:
                type: string
              example: Management from a mocked response!
      x-kusk:
        upstream:
          service:
            name: smart-home-management
            namespace: default
            port: 8080
  /api/v1/telemetry/devices:
    get:
      responses:
        '200':
          description: A simple telemetry!
          content:
            text/plain:
              schema:
                type: string
              example: Telemetry from a mocked response!
      x-kusk:
        upstream:
          service:
            name: smart-home-telemetry
            namespace: default
            port: 8080
