spring:
  application:
    name: management
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home_management
    username: your_username
    password: your_password
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql

server:
  port: 8080
