openapi: '3.0.0'
info:
  title: Smart Home Monolith API
  version: '1.0.0'
paths:
  /api/heating/{id}:
    get:
      summary: Fetching heating system with id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of heating system
          schema:
            type: number
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  isOn:
                    type: boolean
                  targetTemperature:
                    type: number
                  currentTemperature:
                    type: number
    put:
      summary: Updating heating system with id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of heating system
          schema:
            type: number
      requestBody:
        description: Update
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                isOn:
                  type: boolean
                targetTemperature:
                  type: number
                currentTemperature:
                  type: number
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  isOn:
                    type: boolean
                  targetTemperature:
                    type: number
                  currentTemperature:
                    type: number
  /api/heating/{id}/turn-on:
    post:
      summary: Turning on heating system with id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of heating system
          schema:
            type: number
      responses:
        '204':
          description: No content
  /api/heating/{id}/turn-off:
    post:
      summary: Turning off heating system with id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of heating system
          schema:
            type: number
      responses:
        '204':
          description: No content
  /api/heating/{id}/set-temperature:
    post:
      summary: Setting target temperature to {} for heating system with id {}
      parameters:
        - name: id
          in: path
          required: true
          description: The id of heating system
          schema:
            type: number
        - name: temperature
          in: query
          required: true
          description: The temperature of heating system
          schema:
            type: number
      responses:
        '204':
          description: No content
  /api/heating/{id}/current-temperature:
    get:
      summary: Fetching current temperature for heating system with id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of heating system
          schema:
            type: number
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: number
