openapi: '3.0.0'
info:
  title: WeatherNow API
  version: '1.0.0'
paths:
  /weather:
    get:
      summary: Get current weather
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  temperature:
                    type: number
                  humidity:
                    type: number
                  timestamp:
                    type: string
                    format: date-time