@startuml
!include C4.puml
!include C4_Context.puml
!include C4_Container.puml
!include C4_Component.puml

title Smart Home Container Diagram

top to bottom direction

Person(user, "User", "A user of the Smart Home")
System(SmartHomeSystem, "Smart Home System", "System managing memberships, schedules, and payments")

Container_Boundary(SmartHomeSystem, "Smart Home System") {
  Container(UI, "User front interface", "React", "Handles user interactions")
  Container(APIGateway, "API Gateway", "Java, Spring", "Handles user interactions")
  Container(Auth, "Authorizations Microservice", "Java, Spring", "Authentication and authorizations users")
  Container(Management, "Management Microservice", "Java, Spring", "Management devices")
  Container(Telemetry, "Telemetry Microservice", "Java, Spring", "Telemetry from devices")
  Container(DatabaseAuth, "Database Authentication and authorizations", "PostgreSQL", "Authentication and authorizations users")
  Container(DatabaseManagement, "Database Management", "PostgreSQL", "Stores management and state of devices")
  Container(DatabaseTelemetry, "Database Telemetry", "ClickHouse", "Stores telemetry data")
  Container(Kafka, "Kafka", "Apache Kafka", "Event bus")
}

System_Ext(devices, "Devices", "External devices for processing")

Rel(user, UI, "Uses the system")
Rel(UI, APIGateway, "Uses the system")
Rel(APIGateway,Auth,"Authentication and authorizations users")
Rel(APIGateway,Management,"Manage devices")
Rel(APIGateway,Telemetry,"Fetching status about devices")
Rel(Auth,DatabaseAuth,"Reads/Writes user and roles")
Rel(Management,DatabaseManagement,"Reads/Writes state of devices")
Rel(Telemetry,DatabaseTelemetry,"Reads/Writes telemetry data")
Rel(Management,Kafka,"Sent command to devices")
Rel(Telemetry,Kafka,"Collect telemetry data from devices")
Rel(devices,Kafka,"Send telemetry")
@enduml