@startuml
!include C4.puml
!include C4_Context.puml
!include C4_Container.puml
!include C4_Component.puml

title Heating System Context Diagram

top to bottom direction

Person(user, "User", "A user of the Heating system")
System(HeatingSystem, "Heating System API", "System managing Heating")
System(HeatingDevice, "Heating Device", "Heating device")

System_Ext(sensors, "Sensors", "External sensors")
System_Ext(sensors, "Sensors", "External sensors")

Rel(user, HeatingSystem, "Uses the system")
Rel(HeatingSystem, HeatingDevice, "Manage devices")
Rel(sensors, HeatingSystem, "Sending telemetry")

@enduml